version: "3.9"
services:
  web:
    image: httpd:alpine
    ports:
      - "8080:80"
    volumes:
      - web-data:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: changeme
    volumes:
      - db-data:/var/lib/mysql
volumes:
  web-data: {}
  db-data: {}
